name: Release

on:
  push:
    paths: 
      - 'apps/docs/**'
    tags-ignore: 
      - 'v*.*.*'

permissions:
  actions: read
  contents: read

jobs:
  docker-build-docs:
    name: Docker Build Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: npm install

      - name: Build and push images
        run: npx nx run-many --target=container --projects=docs --parallel=2 --configuration=ci
        env:
          INPUT_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
